/* Generated By:JavaCC: Do not edit this line. SoarParserConstants.java */
package com.soartech.soar.ide.core.ast;

public interface SoarParserConstants {

  int EOF = 0;
  int RARROW = 7;
  int SAME_TYPE = 8;
  int GEQUAL = 9;
  int LDISJUNCT = 10;
  int LEQUAL = 11;
  int NEQUAL = 12;
  int RDISJUNCT = 13;
  int AMPERSAND = 14;
  int ATSIGN = 15;
  int CARET = 16;
  int COMMA = 17;
  int EMARK = 18;
  int EQUAL = 19;
  int GREATER = 20;
  int HYPHEN = 21;
  int LBRACE = 22;
  int LESS = 23;
  int LPAREN = 24;
  int PERIOD = 25;
  int PLUS = 26;
  int QMARK = 27;
  int RBRACE = 28;
  int RPAREN = 29;
  int TILDE = 30;
  int LSQBRACET = 31;
  int RSQBRACET = 32;
  int QUOTE = 33;
  int PRODTYPE = 34;
  int VARIABLE = 35;
  int INTEGER_CONST = 36;
  int SYMBOLIC_CONST = 37;
  int FLOATING_POINT_CONST = 38;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "<token of kind 1>",
    "<token of kind 2>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"-->\"",
    "\"<=>\"",
    "\">=\"",
    "\"<<\"",
    "\"<=\"",
    "\"<>\"",
    "\">>\"",
    "\"&\"",
    "\"@\"",
    "\"^\"",
    "\",\"",
    "\"!\"",
    "\"=\"",
    "\">\"",
    "\"-\"",
    "\"{\"",
    "\"<\"",
    "\"(\"",
    "\".\"",
    "\"+\"",
    "\"?\"",
    "\"}\"",
    "\")\"",
    "\"~\"",
    "\"[\"",
    "\"]\"",
    "\"\\\"\"",
    "<PRODTYPE>",
    "<VARIABLE>",
    "<INTEGER_CONST>",
    "<SYMBOLIC_CONST>",
    "<FLOATING_POINT_CONST>",
  };

}
